apiVersion: v1
kind: Service
metadata:
  name: licensingnpservice-srv
spec:
  type: NodePort
  selector:
    app: licensingservice
  ports:
    - name: licensingservice
      protocol: TCP
      port: 80
      targetPort: 8080